databases:
  - name: aura-postgres
    databaseName: aura_farming
    user: aura_farming
    region: virginia
    plan: 0.5c-1g
    postgresMajorVersion: "18"
    connectionPool: pgbouncer
    ipAllowList: []

services:
  - type: web
    name: aura-league-fame
    runtime: node
    region: virginia
    plan: 1c-2g

    buildCommand: npm ci && npm run build
    startCommand: npm start
    autoDeployTrigger: commit

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aura-postgres
          property: connectionPoolString

      - key: NITRO_PRESET
        value: render-com

      - key: HOST
        value: 0.0.0.0

      - key: NODE_VERSION
        value: 22.22.0

      - key: RIOT_API_KEY
        sync: false
